version: 2.1

jobs:
  install-and-test:
    parameters:
      cache_dependencies:
        type: boolean
        default: false

    docker:
      - image: circleci/node:12.13.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci
      - when:
          condition: <<parameters.cache_dependencies>>
          steps:
            - save_cache:
                name: Save dependency cache
                key:
                  v1-depencencies-{{ arch }}-{{ checksum "package-lock.json" }}
                paths:
                  - node_modules/

      - run:
          name: Run tests
          command: |
            npm run test:ci
            bin/check-git

  deploy-docs:
    parameters:
      use_cache:
        type: boolean
        default: false

    docker:
      - image: circleci/node:12.13.0

    steps:
      - checkout

      - add_ssh_keys:
          name: Add GitHub SSH key
          fingerprints:
            - "a9:89:6c:c2:c0:b5:dd:a0:f1:66:dd:e8:83:72:55:dd"
      - run:
          name: Set up Git user
          command: |
            git config user.email "ci@hackney"
            git config user.name "CI"

      - when:
          condition: <<parameters.use_cache>>
          steps:
            - restore_cache:
                name: Restore dependency cache
                key:
                  v1-depencencies-{{ arch }}-{{ checksum "package-lock.json" }}

      - unless:
          condition: <<parameters.use_cache>>
          steps:
            - run:
                name: Install dependencies
                command: npm ci

      - run:
          name: Build docs
          command: |
            npm run build:docs
            bin/check-git
      - run:
          name: Commit and deploy docs to GitHub pages
          command: |
            git checkout gh-pages
            git reset --hard origin/gh-pages
            rm -r docs/
            cp -r tmp/docs docs
            git add docs
            git commit -m "Update the docs to match $CIRCLE_SHA1"
            git push origin gh-pages

workflows:
  check:
    jobs:
      - install-and-test:
          name: install-and-test-branch
          filters:
            branches:
              ignore: master

  check-and-deploy-docs:
    jobs:
      - install-and-test:
          name: install-and-test-master
          filters:
            branches:
              only: master
          cache_dependencies: true

      - deploy-docs:
          requires:
            - install-and-test-master
          use_cache: true
